### ISSUE TITLE
Can't find .\oauth.ini when running OAuth2Util.OAuth2Util(r)

### ISSUE THREAD

**Issue by bluMyst** [SmBe19/praw-OAuth2Util#17]
```
PS C:\Users\foo> python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import praw
>>> import OAuth2Util
>>> r = praw.Reddit("Test Bot Please Ignore")
:0: UserWarning: The keyword `bot` in your user_agent may be problematic.
>>> r = praw.Reddit("Test Script Please Ignore")
>>> o = OAuth2Util.OAuth2Util(r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\OAuth2Util\OAuth2Util.py", line 123, in __init__
    raise FNFError("File " + configfile + " not found")
FileNotFoundError: File C:\Users\foo\oauth.ini not found
>>>
```

It always checks in the current directory for oauth.ini

**Comment by SmBe19** [comment]
That's the expected behavior. Where should it check in your opinion?

**Comment by bluMyst** [comment]
Oh! I was following [this quickstart guide](https://github.com/SmBe19/praw-OAuth2Util/blob/master/OAuth2Util/README.md) and got confused when the example code didn't run. I guess I should've read the whole thing before trying it out. Sorry!

Although I will say, it'd be good if you could mention the need for a config file higher up.

Edit: How do I close this issue?
